### PR TITLE
feat: add custom call for action link (#69)

### PR DESCRIPTION
**Pull request by aouahib**

### CODE REVIEW

**Comment by aouahib** [comment]
Current dependencies on/for this PR:
* main
  * **PR #153** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/153" target="_blank">Graphite</a> 
    * **PR #155** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/155" target="_blank">Graphite</a> 
      * **PR #156** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/156" target="_blank">Graphite</a> 
        * **PR #157** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/157" target="_blank">Graphite</a> 
          * **PR #158** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/158" target="_blank">Graphite</a> 
            * **PR #159** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/159" target="_blank">Graphite</a> 
              * **PR #160** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/160" target="_blank">Graphite</a> 
                * **PR #161** <a href="https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/161" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/161?utm_source=stack-comment).

**Review by andrewszucs — APPROVED** [review]
Ah haha, I actually think this is a smart solution! 😄 Trades Dashboard is a pretty ambiguous title and if you just point the link to a different place of the same implementation it won't be that confusing I don't think. So yeah this is definitely fine for now. If anyone asks for more later, we'll tackle it then. Thanks!!

**Comment by aouahib** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/161?utm_source=stack-comment).


Job Reference: LhE62Pbrj0P1k6gpAemc

**Comment by aouahib** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/metastreet-labs/metastreet-sdk/161?utm_source=stack-comment).


Job Reference: W6it8zzsk3uVZvwrcgQc

**Pull request merged**
